const API_URL="https://script.google.com/macros/s/AKfycbxoN5GYrT2wtHgx2oDhvKhzTDBslMktbL5NHOLlHmuBmCRoxcU3wskVNkLn94PXZJOL/exec";
let state={user:null,staff:[],leaves:[]};
const app=document.getElementById("app"),nav=document.getElementById("nav"),toast=document.getElementById("toast");
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function normDate(v){if(v==null)return"";let s=String(v).trim();let m=s.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);if(m)return `${m[1]}-${String(m[2]).padStart(2,"0")}-${String(m[3]).padStart(2,"0")}`;m=s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})/);return m?`${m[3]}-${String(m[2]).padStart(2,"0")}-${String(m[1]).padStart(2,"0")}`:s}
function fmt(v){const s=normDate(v),p=s.split("-");if(p.length!==3)return s||"—";const mon=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];return `${p[2]} ${mon[Number(p[1])-1]||p[1]} ${p[0]}`}
function msg(t,ok=true){toast.innerHTML=`<div class="toast ${ok?"":"bad"}">${ok?"✓":"!"} ${t}</div>`;setTimeout(()=>toast.innerHTML="",2500)}
document.addEventListener("pointerdown",e=>{const b=e.target.closest("button");if(b){b.classList.add("tap");setTimeout(()=>b.classList.remove("tap"),150)}})
async function api(action,data={}){const r=await fetch(API_URL,{method:"POST",body:JSON.stringify({action,...data})});return r.json()}
async function sync(){const [s,l]=await Promise.all([api("staff"),api("leaves")]);state.staff=s.staff||[];state.leaves=(l.leaves||[]).map(x=>({LeaveID:String(x.LeaveID||""),Staff:String(x.Staff||""),LeaveDate:normDate(x.LeaveDate),DutyBy:String(x.DutyBy||""),Reason:String(x.Reason||""),Status:String(x.Status||""),Owner1Approval:String(x.Owner1Approval||""),Owner2Approval:String(x.Owner2Approval||"")}));localStorage.setItem("sd-final",JSON.stringify({staff:state.staff,leaves:state.leaves}))}
function isOwner(){return !!state.user && /owner/i.test(String(state.user.role||""))}
function login(){nav.innerHTML="";app.innerHTML=`<div class="login"><div class="loginbox"><h1>StaffDuty</h1><p>Leave & duty management</p><label>Username<input id="un"></label><label>PIN<input id="pin" type="password"></label><button class="primary full" onclick="doLogin()">Login</button></div></div>`}
async function doLogin(){try{const r=await api("login",{username:un.value.trim(),pin:pin.value});if(!r.ok)return msg(r.error,false);state.user=r.user;sessionStorage.setItem("sd-user",JSON.stringify(r.user));await sync();go("home")}catch(e){msg(e.message,false)}}
function shell(page,title,body){app.innerHTML=`<div class="wrap"><header><b>StaffDuty</b><small>${state.user.name} · ${state.user.role}</small></header><main><h2>${title}</h2>${body}</main></div>`;nav.innerHTML=[["home","🏠","Home"],["calendar","📅","Calendar"],["apply","＋","Leave"],["approvals","✓","Approval"],["more","☰","More"]].map(x=>`<button class="${page===x[0]?"on":""}" onclick="go('${x[0]}')">${x[1]}<small>${x[2]}</small></button>`).join("")}
function card(x,canRemove=false){return `<div class="card"><div class="row"><b>${x.Staff||"—"}</b><b class="date">${fmt(x.LeaveDate)}</b></div><p>Duty by <b>${x.DutyBy||"—"}</b><br>Reason: ${x.Reason||"—"}</p><span class="badge ${x.Status.toLowerCase()}">${x.Status||"Pending"}</span>${canRemove?`<button class="danger full remove" onclick="removeLeave('${x.LeaveID}')">Remove leave</button>`:""}</div>`}
function home(){shell("home","Dashboard",`<div class="hero"><span>Absent today</span><b>${state.leaves.filter(x=>x.LeaveDate===today()&&x.Status==="Approved").length}</b></div><div class="switch"><button id="abs" class="on" onclick="homeList('abs')">Absent Today</button><button id="up" onclick="homeList('up')">Upcoming Leave</button></div><div id="list"></div>`);homeList("abs")}
function homeList(k){abs.classList.toggle("on",k==="abs");up.classList.toggle("on",k==="up");let a=k==="abs"?state.leaves.filter(x=>x.LeaveDate===today()&&x.Status==="Approved"):state.leaves.filter(x=>x.LeaveDate>=today()&&x.Status!=="Rejected").sort((a,b)=>a.LeaveDate.localeCompare(b.LeaveDate));list.innerHTML=a.length?a.map(x=>card(x,k==="up"&&isOwner())).join(""):'<div class="empty">No leave records.</div>'}
function apply(){const me=state.user.name,others=state.staff.filter(x=>x.Name!==me);shell("apply","Report Leave",`<div class="card"><label>Staff<input value="${me}" readonly></label><label>Leave date<input id="dt" type="date" min="${today()}"></label><label>Duty will be done by<select id="cv"><option value="">Select replacement</option>${others.map(x=>`<option>${x.Name}</option>`).join("")}</select></label><label>Reason<textarea id="rs" rows="3"></textarea></label><button class="primary full" onclick="submitLeave()">Submit for approval</button></div>`)}
async function submitLeave(){const date=String(dt.value||"").trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<today())return msg("Please select a correct future date",false);if(!cv.value)return msg("Select replacement staff",false);try{const r=await api("createLeave",{staff:state.user.name,date,cover:cv.value,reason:rs.value});if(!r.ok)return msg(r.error,false);await sync();msg("Leave submitted successfully ✓");go("home")}catch(e){msg(e.message,false)}}
function approvals(){if(!isOwner())return shell("approvals","Owner Approval",'<div class="empty">Owner access required.</div>');const pending=state.leaves.filter(x=>x.Status==="Pending");shell("approvals","Owner Approval",`${pending.length?'<h3>Pending</h3>'+pending.map(x=>`<div class="card"><div class="row"><b>${x.Staff}</b><b class="date">${fmt(x.LeaveDate)}</b></div><p>Duty by <b>${x.DutyBy}</b><br>Reason: ${x.Reason||"—"}</p><div class="actions"><button class="primary" onclick="approve('${x.LeaveID}')">✓ Approve</button><button class="danger" onclick="reject('${x.LeaveID}')">Reject</button></div><button class="danger full remove" onclick="removeLeave('${x.LeaveID}')">Remove leave</button></div>`).join(""):'<div class="empty">No pending approvals.</div>'}<h3>Approved leaves</h3>${state.leaves.filter(x=>x.Status==="Approved").map(x=>card(x,true)).join("")||'<div class="empty">No approved leaves.</div>'}`)}
async function approve(id){const r=await api("approve",{id,username:state.user.username});if(!r.ok)return msg(r.error,false);await sync();msg("Approval recorded ✓");go("approvals")}
async function reject(id){const r=await api("reject",{id,username:state.user.username});if(!r.ok)return msg(r.error,false);await sync();msg("Leave rejected");go("approvals")}
async function removeLeave(id){if(!isOwner())return msg("Owner access required",false);if(!confirm("Remove this leave permanently?"))return;try{const r=await api("removeLeave",{id:String(id),username:String(state.user.username)});if(!r.ok)return msg(r.error||"Unable to remove leave",false);await sync();msg("Leave removed ✓");go("home")}catch(e){msg(e.message,false)}}
function calendar(){shell("calendar","Leave Calendar",'<div class="empty">Upcoming leaves are shown on Home → Upcoming Leave.</div>')}
function more(){shell("more","More",`<div class="card"><b>${state.user.name}</b><p>${state.user.role}</p></div><div class="card"><b>Change password</b><label>Current PIN<input id="oldpin" type="password"></label><label>New PIN<input id="newpin" type="password"></label><label>Confirm PIN<input id="confpin" type="password"></label><button class="primary full" onclick="changePassword()">Change password</button></div><div class="card"><button class="secondary full" onclick="logout()">Log out</button></div>`)}
async function changePassword(){if(!oldpin.value||!newpin.value||newpin.value!==confpin.value)return msg("Check PIN fields",false);const r=await api("changePassword",{username:state.user.username,oldPin:oldpin.value,newPin:newpin.value});if(!r.ok)return msg(r.error,false);msg("Password changed ✓")}
function logout(){sessionStorage.removeItem("sd-user");state.user=null;login()}
async function go(p){if(!state.user)return login();({home,calendar,apply,approvals,more}[p])()}
try{const x=JSON.parse(localStorage.getItem("sd-final")||"{}");state.staff=x.staff||[];state.leaves=x.leaves||[]}catch(e){}
try{const u=JSON.parse(sessionStorage.getItem("sd-user")||"null");if(u){state.user=u;go("home");sync()}else login()}catch(e){login()}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
