const API_URL="https://script.google.com/macros/s/AKfycbxoN5GYrT2wtHgx2oDhvKhzTDBslMktbL5NHOLlHmuBmCRoxcU3wskVNkLn94PXZJOL/exec";
let S={user:null,staff:[],leaves:[]};

function today(){let d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function nd(v){let s=String(v||"").trim(),m=s.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);return m?m[1]+"-"+("0"+m[2]).slice(-2)+"-"+("0"+m[3]).slice(-2):s}
function fd(v){let p=nd(v).split("-"),m=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];return p.length==3?p[2]+" "+m[+p[1]-1]+" "+p[0]:String(v||"—")}
function toast(x,b=true){document.getElementById("toast").innerHTML='<div class="toast '+(b?"":"bad")+'">'+(b?"✓ ":"! ")+x+'</div>';setTimeout(()=>document.getElementById("toast").innerHTML="",2500)}
async function api(action,data={}){let r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,...data})});return r.json()}
function owner(){return !!S.user&&/owner/i.test(String(S.user.role))}
async function sync(){let[l,s]=await Promise.all([api("leaves"),api("staff")]);S.leaves=l.leaves||[];S.staff=s.staff||[];localStorage.setItem("sd-one",JSON.stringify(S))}
function login(){document.getElementById("nav").innerHTML="";document.getElementById("app").innerHTML='<div class="login"><div class="box"><div class="brand">StaffDuty</div><p class="muted">Staff Leave & Duty Management</p><label>Username<input id="un" autocomplete="username"></label><label>PIN<input id="pin" type="password" inputmode="numeric" autocomplete="current-password"></label><button class="primary full" onclick="doLogin()">Login</button></div></div>'}
async function doLogin(){let r=await api("login",{username:un.value.trim(),pin:pin.value});if(!r.ok)return toast(r.error,false);S.user=r.user;sessionStorage.setItem("sd-user",JSON.stringify(r.user));await sync();go("home")}
function shell(p,t,b){document.getElementById("app").innerHTML='<header><div><b>StaffDuty</b><small>'+S.user.name+" · "+S.user.role+'</small></div><button class="headLogout" onclick="logout()">Logout</button></header><main><h2>'+t+"</h2>"+b+"</main>";document.getElementById("nav").innerHTML=[["home","🏠","Home"],["apply","＋","Leave"],["approvals","✓","Approval"],["more","☰","More"]].map(x=>'<button class="'+(p==x[0]?"on":"")+'" onclick="go(\''+x[0]+'\')">'+x[1]+'<small>'+x[2]+"</small></button>").join("")}
function leaveDates(x){let s=nd(x.StartDate||x.LeaveDate),e=nd(x.EndDate||x.StartDate||x.LeaveDate);return s===e?fd(s):fd(s)+" – "+fd(e)}
function leaveTypeLabel(t){t=String(t||"Full Day");return t.replace("Half Day -","Half Day –")}
function card(x,rm){return '<div class="card"><div class="row"><b>'+x.Staff+'</b><b class="date">'+leaveDates(x)+'</b></div><p>'+leaveTypeLabel(x.LeaveType)+'<br>Duty by <b>'+x.DutyBy+'</b><br>Reason: '+(x.Reason||"—")+'</p><span class="badge">'+x.Status+"</span>"+(rm?'<button class="danger full remove" onclick="removeLeave(\''+x.LeaveID+'\')">Remove leave</button>':"")+"</div>"}
function home(){shell("home","Dashboard",'<div class="hero"><span>Absent today</span><b>'+S.leaves.filter(x=>nd(x.StartDate||x.LeaveDate)<=today()&&nd(x.EndDate||x.StartDate||x.LeaveDate)>=today()&&x.Status=="Approved").length+'</b></div><div class="switch"><button id="ab" class="on" onclick="listHome(0)">Absent Today</button><button id="up" onclick="listHome(1)">Upcoming Leave</button></div><div id="list"></div>');listHome(0)}
function listHome(k){document.getElementById("ab").classList.toggle("on",!k);document.getElementById("up").classList.toggle("on",!!k);let a=k?S.leaves.filter(x=>nd(x.EndDate||x.StartDate||x.LeaveDate)>=today()&&x.Status!="Rejected").sort((a,b)=>nd(a.StartDate||a.LeaveDate).localeCompare(nd(b.StartDate||b.LeaveDate))):S.leaves.filter(x=>nd(x.StartDate||x.LeaveDate)<=today()&&nd(x.EndDate||x.StartDate||x.LeaveDate)>=today()&&x.Status=="Approved");document.getElementById("list").innerHTML=a.length?a.map(x=>card(x,k&&owner())).join(""):'<div class="empty">No leave records.</div>'}
function apply(){let o=S.staff.filter(x=>x.Name!=S.user.name);shell("apply","Report Leave",'<div class="card"><label>Staff<input value="'+S.user.name+'" readonly></label><label>Start date<input id="sd" type="date" min="'+today()+'" onchange="dateChanged()"></label><label>End date<input id="ed" type="date" min="'+today()+'"></label><label>Leave type<select id="lt" onchange="toggleHalfDay()"><option>Full Day</option><option>Half Day – Morning</option><option>Half Day – Evening</option></select></label><label>Duty will be done by<select id="cv"><option value="">Select replacement</option>'+o.map(x=>"<option>"+x.Name+"</option>").join("")+'</select></label><label>Reason<textarea id="rs"></textarea></label><button class="primary full" onclick="submitLeave()">Submit for approval</button></div>');sd.value=today();ed.value=today();dateChanged()}
function dateChanged(){ed.min=sd.value;if(lt.value!=="Full Day")ed.value=sd.value;else if(ed.value<sd.value)ed.value=sd.value}
function toggleHalfDay(){let half=lt.value!=="Full Day";ed.disabled=half;if(half)ed.value=sd.value}
async function submitLeave(){let start=String(sd.value||""),end=String(ed.value||start),type=String(lt.value||"Full Day");if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||start<today())return toast("Please select a correct future start date",false);if(!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<start)return toast("Please select a correct end date",false);if(type!=="Full Day"&&end!==start)return toast("Half-day leave must be for one day",false);if(!cv.value)return toast("Select replacement staff",false);let r=await api("createLeave",{staff:S.user.name,startDate:start,endDate:end,leaveType:type,cover:cv.value,reason:rs.value});if(!r.ok)return toast(r.error,false);await sync();toast("Leave submitted successfully");go("home")}
function approvals(){if(!owner())return shell("approvals","Owner Approval",'<div class="empty">Owner access required.</div>');let p=S.leaves.filter(x=>x.Status=="Pending"),a=S.leaves.filter(x=>x.Status=="Approved");shell("approvals","Owner Approval",(p.length?p.map(x=>'<div class="card"><div class="row"><b>'+x.Staff+'</b><b class="date">'+leaveDates(x)+'</b></div><p>'+leaveTypeLabel(x.LeaveType)+'<br>Duty by <b>'+x.DutyBy+'</b><br>Reason: '+(x.Reason||"—")+'</p><div class="actions"><button class="primary" onclick="approve(\''+x.LeaveID+'\')">✓ Approve</button><button class="danger" onclick="reject(\''+x.LeaveID+'\')">Reject</button></div><button class="danger full remove" onclick="removeLeave(\''+x.LeaveID+'\')">Remove leave</button></div>').join(""):'<div class="empty">No pending approvals.</div>')+'<h3>Approved leaves</h3>'+ (a.length?a.map(x=>card(x,true)).join(""):'<div class="empty">No approved leaves.</div>'))}
async function approve(id){let r=await api("approve",{id,username:S.user.username});if(!r.ok)return toast(r.error,false);await sync();toast("Leave approved");go("approvals")}
async function reject(id){let r=await api("reject",{id,username:S.user.username});if(!r.ok)return toast(r.error,false);await sync();toast("Leave rejected");go("approvals")}
async function removeLeave(id){if(!owner())return toast("Owner access required",false);if(!confirm("Remove this leave permanently?"))return;let r=await api("removeLeave",{id,username:S.user.username});if(!r.ok)return toast(r.error,false);await sync();toast("Leave removed");go("home")}
function more(){shell("more","More",'<div class="card"><b>'+S.user.name+'</b><p>'+S.user.role+'</p></div><div class="card"><b>Change password</b><label>Current PIN<input id="oldpin" type="password" inputmode="numeric"></label><label>New PIN<input id="newpin" type="password" inputmode="numeric"></label><label>Confirm PIN<input id="cpin" type="password" inputmode="numeric"></label><button class="primary full" onclick="changePassword()">Change password</button></div>'+(owner()?'<div class="card"><b>Monthly Summary</b><label>Month<input id="sumMonth" type="month" value="'+today().slice(0,7)+'"></label><button class="primary full" onclick="showSummary()">View summary</button><div id="summary"></div></div>':"")+'<div class="card logoutCard"><button class="danger full" onclick="logout()">Log out</button></div>')}
async function changePassword(){if(!oldpin.value||!newpin.value||newpin.value!=cpin.value)return toast("Check PIN fields",false);let r=await api("changePassword",{username:S.user.username,oldPin:oldpin.value,newPin:newpin.value});if(!r.ok)return toast(r.error,false);toast("Password changed")}
async function showSummary(){let r=await api("monthlySummary",{username:S.user.username,month:sumMonth.value});if(!r.ok)return toast(r.error,false);summary.innerHTML='<div class="tableWrap"><table class="summary"><tr><th>Staff</th><th>Full</th><th>AM</th><th>PM</th><th>Total</th></tr>'+r.summary.map(x=>'<tr><td>'+x.Staff+'</td><td>'+x.FullDays+'</td><td>'+x.Morning+'</td><td>'+x.Evening+'</td><td><b>'+x.Total+'</b></td></tr>').join("")+'</table></div>'}
function logout(){sessionStorage.removeItem("sd-user");S.user=null;login()}
function go(p){if(!S.user)return login();({home,apply,approvals,more}[p]||home)()}
try{let x=JSON.parse(localStorage.getItem("sd-one")||"{}");S.staff=x.staff||[];S.leaves=x.leaves||[]}catch(e){}
try{S.user=JSON.parse(sessionStorage.getItem("sd-user")||"null")}catch(e){}
S.user?go("home"):login();
window.addEventListener("click",e=>{let b=e.target.closest("button");if(b){b.classList.remove("tap");void b.offsetWidth;b.classList.add("tap");setTimeout(()=>b.classList.remove("tap"),160)}});